### ISSUE TITLE
after installing with yarn global can't run with custom conf

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/spacebro-client-cli#2]
Trying to run: 

`spacebro-client-cli my-config.json` as per the doc, throw `zsh: command not found: spacebro-client-cli`

Running:

`spacebro-client spacebro.conf` throw:

```
SyntaxError: Unexpected token :
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gabrielstuff/.config/yarn/global/node_modules/spacebro-client-cli/index.js:18:12)
```

JSON looks like this: 

```
{
  "clientName": "spacebro-client-CLI",
  "spacebro": {
    "address": "192.168.1.233",
    "port": 8888
  }
}
```

**Comment by gabrielstuff** [comment]
Ok, my mistake. Was using the `.conf ` extension instead of `.json`, which could be nice actually :)
